Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -5,21 +5,22 @@ pipeline {
         stage('Clone Code') {
             steps {
                 echo 'Cloning the code from GitHub...'
-                git 'https://github.com/sohitji725/jenkins-demo.git'
+                // If the repository is private, use credentials
+                git url: 'https://github.com/sohitji725/jenkins-demo.git' // Add credentialsId if needed
             }
         }
 
         stage('List Files') {
             steps {
                 echo 'Listing all files...'
-                sh 'ls -l'
+                sh 'ls -l' // Use 'dir' if running on a Windows agent
             }
         }
 
         stage('Show HTML') {
             steps {
                 echo 'Printing index.html content...'
-                sh 'cat index.html'
+                sh 'cat index.html || echo "index.html file not found"' // Use 'type index.html' on Windows
             }
         }
     }
